## Requirements

In [1]:
import sys

import numpy as np
import torch

## Tensor basics

PyTorch tensors can be created in multiple ways.  The most basic is initialization from a Python (nested) list.

In [2]:
t1 = torch.tensor([1.0, 3.0, 7.0], dtype=torch.float64)

In [3]:
t2 = torch.tensor([
    [3.1, 2.4, 5.7],
    [1.9, 12.3, 2.6],
])

### Tensor attributes

Similar to numpy arrays, PyTorch tensors have many attributes.

In [4]:
t1.shape, t2.shape

(torch.Size([3]), torch.Size([2, 3]))

In [5]:
t1.dtype, t2.dtype

(torch.float64, torch.float32)

Contrary to what you might expect, the default `dtype` of a PyTorch tensor is `torch.float32`, not double precision as you are used to in numpy.

Attributes that are specific to PyTorch tensors are the device it is on, and whether gradients are required.

In [6]:
t1.device, t1.requires_grad

(device(type='cpu'), False)

By default, the device is the CPU, i.e., the host device, and no gradients are required.

### Initialization

Similar to numpy, PyTorch has a number of built-in functions to initialize tensors.  Below are a few examples.

In [7]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.randn(2, 3, 2)

tensor([[[ 0.5219,  0.1576],
         [ 0.8565, -0.6006],
         [-0.2756,  0.1271]],

        [[ 0.9766, -1.7953],
         [ 0.5326, -0.4391],
         [ 0.9004,  0.1726]]])

In [10]:
torch.empty(5)

tensor([-2.4468e-17,  4.2203e-41, -1.9479e-14,  3.4682e-41,  0.0000e+00])

## Tensor operations

As you would expect, arithmetic operations are defined on Pytorch tensors.  Similar to numpy, broadcasting is supported.

In [11]:
t1 = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
])

In [12]:
2.0 + t1

tensor([[3., 4.],
        [5., 6.]])

In [13]:
0.5*t1

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [14]:
t1**2

tensor([[ 1.,  4.],
        [ 9., 16.]])

When operating on tensors, shapes should match.

In [15]:
t2 = torch.tensor([
    [0.1, 0.2],
    [0.3, 0.4],
])

In [16]:
t1 + t2, t1*t2

(tensor([[1.1000, 2.2000],
         [3.3000, 4.4000]]),
 tensor([[0.1000, 0.4000],
         [0.9000, 1.6000]]))

Note that the operations are element-wise.

In [17]:
t3 = torch.tensor([
    [-1.0, 0.0, 1.0],
    [1.0, 0.0, -1.0],
])

In [18]:
try:
    t1 + t3
except Exception as e:
    print(e, file=sys.stderr)

The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


However, broadcasting works when shapes match.

In [19]:
t4 = torch.tensor([10.0, 20.0])

In [20]:
t4 + t1

tensor([[11., 22.],
        [13., 24.]])

Operations can be done in place, explicitely using the `add_`, `subtract_`, `multiply_` and `divide_` methods.

In [21]:
t4.subtract_(1.0)

tensor([ 9., 19.])

Matrix multiplication can be done using the `@` operator.

In [22]:
t5 = torch.rand(2, 3)
t6 = torch.rand(3, 4)
t5, t6, t5@t6

(tensor([[0.6039, 0.4147, 0.7988],
         [0.8561, 0.6574, 0.9251]]),
 tensor([[0.3971, 0.6389, 0.5313, 0.8186],
         [0.6357, 0.2963, 0.6215, 0.9515],
         [0.5241, 0.2777, 0.3573, 0.5848]]),
 tensor([[0.9221, 0.7305, 0.8640, 1.3561],
         [1.2427, 0.9986, 1.1940, 1.8673]]))

## Indexing

Indexing tensors is very similar to numpy arrays.  FAncy indexing works as well.

In [23]:
t = torch.randn(3, 4)

In [24]:
t

tensor([[-0.0427,  0.3275,  0.5494, -0.3665],
        [ 0.1741, -2.3084, -0.5032, -0.2944],
        [ 0.4861, -0.5477, -0.9698, -1.9089]])

In [25]:
t[1, 2]

tensor(-0.5032)

In [26]:
t[:, 1]

tensor([ 0.3275, -2.3084, -0.5477])

In [27]:
t[t < 0.0] = 0.0

In [28]:
t

tensor([[0.0000, 0.3275, 0.5494, 0.0000],
        [0.1741, 0.0000, 0.0000, 0.0000],
        [0.4861, 0.0000, 0.0000, 0.0000]])

## Reshaping

A common operation on a tensor is reshaping it, i.e., modifying its rank.  In PyTorch, this is done by creating a view on the tensor.

In [29]:
t = torch.arange(1, 25)

In [30]:
t.shape

torch.Size([24])

In [31]:
v = t.view(4, 6)

In [32]:
v.shape

torch.Size([4, 6])

A view is exactly that, so in the example above, both `t` and `v` refer to the same data.

In [33]:
v[1, 1] = -1

In [34]:
t

tensor([ 1,  2,  3,  4,  5,  6,  7, -1,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

Flattening a tensor is simple.

In [35]:
v1 = v.view(-1)

In [36]:
v1.shape

torch.Size([24])

You can add another dimension to a view using `unsqueeze`.

In [37]:
v2 = v1.unsqueeze(0)

In [38]:
v2.shape

torch.Size([1, 24])

In [39]:
v3 = v1.unsqueeze(1)

In [40]:
v3.shape

torch.Size([24, 1])

In [41]:
v4 = v2.unsqueeze(2)

In [42]:
v4.shape

torch.Size([1, 24, 1])

The reverse operation, `squeeze`, removes a dimension if it is 1.

In [43]:
v4.squeeze(0).shape

torch.Size([24, 1])

In [44]:
v4.squeeze(2).shape

torch.Size([1, 24])

In [45]:
v4.squeeze(1).shape

torch.Size([1, 24, 1])

## 
Conversions

The result of a computation involving tensors is a tensor, even when the result is a single number.

In [46]:
t = torch.rand(3, 3).sum()

In [47]:
t

tensor(4.2559)

To get a number, use the `item()` method.

In [48]:
t.item()

4.255926609039307

Note that this is a Python `float value.

You can also easily convert a numpy array to and from a PyTorch tensor.

In [49]:
data = np.random.uniform(size=(3, 4))

In [50]:
t = torch.from_numpy(data)

In [51]:
t.dtype

torch.float64

In [52]:
t = t.to(torch.float32)

In [53]:
t.dtype

torch.float32

t1 = torch.rand(3, 4)

In [54]:
data1 = t1.numpy()

In [55]:
data.shape, data.dtype

((3, 4), dtype('float64'))

## Devices

You can check whether a CUDA device is available.

In [56]:
torch.cuda.is_available()

True

In [57]:
torch.cuda.device_count()

1

You can move a tensor from the host to a device.

In [58]:
t_host = torch.rand(3, 4)

In [59]:
t_host.device

device(type='cpu')

In [60]:
if torch.cuda.is_available():
    t_dev = t_host.to('cuda')
    print(f'device is {t_dev.device}')
    t_dev[0, 0] = -1.0
    print(t_dev)

device is cuda:0
tensor([[-1.0000,  0.2456,  0.5680,  0.5148],
        [ 0.3087,  0.3336,  0.0437,  0.4458],
        [ 0.3451,  0.2805,  0.1695,  0.5190]], device='cuda:0')


The tensor on the host has not changed.

In [61]:
t_host

tensor([[0.2740, 0.2456, 0.5680, 0.5148],
        [0.3087, 0.3336, 0.0437, 0.4458],
        [0.3451, 0.2805, 0.1695, 0.5190]])

In [62]:
if torch.cuda.is_available():
    t1_host = t_dev.to('cpu')
    print(t1_host)

tensor([[-1.0000,  0.2456,  0.5680,  0.5148],
        [ 0.3087,  0.3336,  0.0437,  0.4458],
        [ 0.3451,  0.2805,  0.1695,  0.5190]])
